name: Run Tests and other CI Steps

on:
  - push
  - pull_request

jobs:
  lints-ci:
    #The lint jobs don't need to run on other OS's or python versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: uv sync --all-extras --group dev
      - name: run lint checks
        run: uv run flake8 alpaca/ tests/
      - name: build doc html to lint for errors
        run: ./tools/scripts/generate-docs.sh

  tests-ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ] #we'll want to add other versions down the road
        os: [ ubuntu-latest ] #in the future we should add windows here
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-extras --group dev
      - name: run tests
        run: uv run pytest
